version: "3.8"

services:
  mvnjobs:
    image: maven:3.8.6-jdk-8-slim
    container_name: camunda
    working_dir: /app
    volumes:
      - ~/uzrnem/camunda/youtube:/app
      - ~/uzrnem/maven:/root/.m2:rw
    ports:
      - 8080:8080
    command: tail -f /dev/null